spring.application.name=crownet-testbed
server.address=${SERVER_ADDRESS}
crownet.testbed.host=${EXPERIMENTAL_WIFI_IP}
crownet.testbed.wifi.broadcast.address=${EXPERIMENTAL_BROADCAST_IP}
crownet.testbed.wifi.broadcast.send-port=${EXPERIMENTAL_WIFI_SENDING_PORT}
crownet.testbed.wifi.broadcast.receive-port=${EXPERIMENTAL_WIFI_RECEIVING_PORT}