# Spring Boot app name
spring.application.name=crownet-testbed
# Host/IP to bind server to
server.address=${SERVER_ADDRESS:0.0.0.0}
# Unique ID of this node
crownet.testbed.adhoc.node-id=${EXPERIMENTAL_NODE_ID:0}
# UDP port for sending beacons
crownet.testbed.adhoc.beacon.send-port=${ADHOC_SEND_PORT:8888}
# UDP port for receiving beacons
crownet.testbed.adhoc.beacon.receive-port=${ADHOC_RECEIVE_PORT:8889}
# Max beacon bandwidth in bytes per second (default 6250 = 50 kbit/s)
crownet.testbed.adhoc.beacon.bandwidth=${ADHOC_BEACON_BANDWIDTH:1000}
# UDP port for sending messages
crownet.testbed.adhoc.message.send-port=${ADHOC_SEND_PORT:9000}
# UDP port for receiving messages
crownet.testbed.adhoc.message.receive-port=${ADHOC_RECEIVE_PORT:9001}
# Max message bandwidth in bytes per second (default 62500 = 500 kbit/s)
crownet.testbed.adhoc.message.bandwidth=${ADHOC_MESSAGE_BANDWIDTH:62500}
# Broadcast IP for ad-hoc network
crownet.testbed.adhoc.broadcast-address=${EXPERIMENTAL_BROADCAST_IP:192.168.1.255}