spring.application.name=crownet-testbed
server.address=${SERVER_ADDRESS}
crownet.testbed.host=${EXPERIMENTAL_WIFI_IP}
crownet.testbed.wifi.broadcast.receive-port=${EXPERIMENTAL_WIFI_RECEIVING_PORT}
crownet.testbed.wifi.broadcast.payload-send-port=${EXPERIMENTAL_PAYLOAD_SENDING_PORT:8890}
crownet.testbed.wifi.broadcast.payload-receive-port=${EXPERIMENTAL_PAYLOAD_RECEIVING_PORT:8889}


crownet.testbed.adhoc.node-id=${EXPERIMENTAL_NODE_ID}
crownet.testbed.adhoc.send-port=${ADHOC_SEND_PORT:8888}
crownet.testbed.adhoc.receive-port=${ADHOC_RECEIVE_PORT:8889}
crownet.testbed.adhoc.broadcast-address=${EXPERIMENTAL_BROADCAST_IP:255.255.255.255}

