[pis]
pi01   ansible_host=192.168.0.3 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=1
pi02   ansible_host=192.168.0.4 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=2
pi03   ansible_host=192.168.0.5 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=3
pi04   ansible_host=192.168.0.6 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=4
pi05   ansible_host=192.168.0.7 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=5
pi06   ansible_host=192.168.0.8 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=6
pi07   ansible_host=192.168.0.9 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=7
pi08   ansible_host=192.168.0.10 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=8
pi09   ansible_host=192.168.0.11 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=9
pi10   ansible_host=192.168.0.12 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=10
pi11   ansible_host=192.168.0.13 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=11
pi12   ansible_host=192.168.0.14 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=12
pi13   ansible_host=192.168.0.15 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=13
pi14   ansible_host=192.168.0.16 ansible_user=ubuntu ansible_connection=paramiko ansible_password=pwdUbuntu experimental_node_id=14

[pis:vars]
ansible_python_interpreter=/usr/bin/python3